### ISSUE TITLE
Need feedback to test how it sounds

### ISSUE THREAD

**Issue by hwpplayer1** [hwpplayers/convergents#1]
I just need feedback.

**Comment by hwpplayer1** [comment]
I tested this application template with Atom and it seems good. So i'll move forward with Atom.

**Comment by theBest3000** [comment]
What's the purpose of this app? What feedback do you need?

**Comment by hwpplayer1** [comment]
I want a suite of social media interaction featured Ubuntu and Canonical projects which you can see what is going on 

Like newspaper but you can watch it and there will be more for administration and development.
